config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'
	resources :calculations
	get '/calculations/new', to: 'calculations#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
	def new
	end

	def create
		a = params[:a].to_f
		b = params[:b].to_f
		c = params[:c].to_f
		d = (b*b) - (4*a*c)
		if a == 0 && b == 0 && c == 0
			render plain: "*"
    elsif (a != 0 && b == 0 && c == 0) || (a == 0 && b != 0 && c == 0)
      render plain: "0.0"
    elsif a != 0 && b == 0 && c != 0
      if (-c/a) > 0
        x = Math.sqrt(-c/a)
        render plain: "#{-(x.round(3))},#{x.round(3)}"
      else
        render plain: "NaN"
      end
    elsif a == 0 && b != 0 && c != 0
      x = -c/b
      x = x.round(3);
      render plain: "#{x}"
		elsif (a == 0 && b == 0 && c != 0) || d < 0
			render plain: "NaN"
    else
      if d > 0
        x = (-b + Math.sqrt(d)) / (2*a)
        x = x.round(3)
        if x == -0.0
          x = 0.0
        end
        y = (-b - Math.sqrt(d)) / (2*a)
        y = y.round(3)
        if y == -0.0
          y = 0.0
        end
        if x < y
            render plain: "#{x},#{y}"
        else
            render plain: "#{y},#{x}"
        end
      else
        x = (-b) / (2*a)
        x = x.round(3)
        render plain: "#{x}"
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculations/create.html.erb
<%=@to_puts%>

app/views/calculations/new.html.erb
<%= form_for :calculation, url: calculations_path,  local: true do |form| %>
  <table>
    <tr>
      <td>
    <%= form.label :a %><br>
    <%= text_field_tag(:a) %>
  </td>

  <td>
    <%= form.label :b %><br>
    <%= text_field_tag(:b) %>
  </td>

  <td>
    <%= form.label :c %><br>
    <%= text_field_tag(:c) %>
  </td>
</tr>

  <tr>
  <td>  <%= form.submit "Solve!" %></td>
  </tr></table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>